$files = @('Protoss_DirectDrop_Zerg_Benzene.txt',
'Protoss_DirectDrop_Zerg_Destination.txt',
'Protoss_DirectDrop_Zerg_Heartbreak Ridge.txt',
'Protoss_DirectDrop_Zerg_Aztec.txt',
'Protoss_DirectDrop_Zerg_Tau Cross.txt',
'Protoss_DirectDrop_Zerg_Andromeda.txt',
'Protoss_DirectDrop_Zerg_Circuit Breaker.txt',
'Protoss_DirectDrop_Zerg_Empire of the Sun.txt',
'Protoss_DirectDrop_Zerg_Fortress.txt',
'Protoss_DirectDrop_Zerg_Python.txt',
'Protoss_Drop_Zerg_Benzene.txt',
'Protoss_Drop_Zerg_Destination.txt',
'Protoss_Drop_Zerg_Heartbreak Ridge.txt',
'Protoss_Drop_Zerg_Aztec.txt',
'Protoss_Drop_Zerg_Tau Cross.txt',
'Protoss_Drop_Zerg_Andromeda.txt',
'Protoss_Drop_Zerg_Circuit Breaker.txt',
'Protoss_Drop_Zerg_Empire of the Sun.txt',
'Protoss_Drop_Zerg_Fortress.txt',
'Protoss_Drop_Zerg_Python.txt',
'Protoss_ZealotRush_Zerg_Benzene.txt',
'Protoss_ZealotRush_Zerg_Destination.txt',
'Protoss_ZealotRush_Zerg_Heartbreak Ridge.txt',
'Protoss_ZealotRush_Zerg_Aztec.txt',
'Protoss_ZealotRush_Zerg_Tau Cross.txt',
'Protoss_ZealotRush_Zerg_Andromeda.txt',
'Protoss_ZealotRush_Zerg_Circuit Breaker.txt',
'Protoss_ZealotRush_Zerg_Empire of the Sun.txt',
'Protoss_ZealotRush_Zerg_Fortress.txt',
'Protoss_ZealotRush_Zerg_Python.txt',
'Protoss_DirectDrop_Terran_Benzene.txt',
'Protoss_DirectDrop_Terran_Destination.txt',
'Protoss_DirectDrop_Terran_Heartbreak Ridge.txt',
'Protoss_DirectDrop_Terran_Aztec.txt',
'Protoss_DirectDrop_Terran_Tau Cross.txt',
'Protoss_DirectDrop_Terran_Andromeda.txt',
'Protoss_DirectDrop_Terran_Circuit Breaker.txt',
'Protoss_DirectDrop_Terran_Empire of the Sun.txt',
'Protoss_DirectDrop_Terran_Fortress.txt',
'Protoss_DirectDrop_Terran_Python.txt',
'Protoss_Drop_Terran_Benzene.txt',
'Protoss_Drop_Terran_Destination.txt',
'Protoss_Drop_Terran_Heartbreak Ridge.txt',
'Protoss_Drop_Terran_Aztec.txt',
'Protoss_Drop_Terran_Tau Cross.txt',
'Protoss_Drop_Terran_Andromeda.txt',
'Protoss_Drop_Terran_Circuit Breaker.txt',
'Protoss_Drop_Terran_Empire of the Sun.txt',
'Protoss_Drop_Terran_Fortress.txt',
'Protoss_Drop_Terran_Python.txt',
'Protoss_ZealotRush_Terran_Benzene.txt',
'Protoss_ZealotRush_Terran_Destination.txt',
'Protoss_ZealotRush_Terran_Heartbreak Ridge.txt',
'Protoss_ZealotRush_Terran_Aztec.txt',
'Protoss_ZealotRush_Terran_Tau Cross.txt',
'Protoss_ZealotRush_Terran_Andromeda.txt',
'Protoss_ZealotRush_Terran_Circuit Breaker.txt',
'Protoss_ZealotRush_Terran_Empire of the Sun.txt',
'Protoss_ZealotRush_Terran_Fortress.txt',
'Protoss_ZealotRush_Terran_Python.txt',
'Protoss_DirectDrop_Protoss_Benzene.txt',
'Protoss_DirectDrop_Protoss_Destination.txt',
'Protoss_DirectDrop_Protoss_Heartbreak Ridge.txt',
'Protoss_DirectDrop_Protoss_Aztec.txt',
'Protoss_DirectDrop_Protoss_Tau Cross.txt',
'Protoss_DirectDrop_Protoss_Andromeda.txt',
'Protoss_DirectDrop_Protoss_Circuit Breaker.txt',
'Protoss_DirectDrop_Protoss_Empire of the Sun.txt',
'Protoss_DirectDrop_Protoss_Fortress.txt',
'Protoss_DirectDrop_Protoss_Python.txt',
'Protoss_Drop_Protoss_Benzene.txt',
'Protoss_Drop_Protoss_Destination.txt',
'Protoss_Drop_Protoss_Heartbreak Ridge.txt',
'Protoss_Drop_Protoss_Aztec.txt',
'Protoss_Drop_Protoss_Tau Cross.txt',
'Protoss_Drop_Protoss_Andromeda.txt',
'Protoss_Drop_Protoss_Circuit Breaker.txt',
'Protoss_Drop_Protoss_Empire of the Sun.txt',
'Protoss_Drop_Protoss_Fortress.txt',
'Protoss_Drop_Protoss_Python.txt',
'Protoss_ZealotRush_Protoss_Benzene.txt',
'Protoss_ZealotRush_Protoss_Destination.txt',
'Protoss_ZealotRush_Protoss_Heartbreak Ridge.txt',
'Protoss_ZealotRush_Protoss_Aztec.txt',
'Protoss_ZealotRush_Protoss_Tau Cross.txt',
'Protoss_ZealotRush_Protoss_Andromeda.txt',
'Protoss_ZealotRush_Protoss_Circuit Breaker.txt',
'Protoss_ZealotRush_Protoss_Empire of the Sun.txt',
'Protoss_ZealotRush_Protoss_Fortress.txt',
'Protoss_ZealotRush_Protoss_Python.txt')

$dir = 'E:\Test\UAlbertaBot\bin\bwapi-data\logging\';
$dir2 = $dir + $files[0];
$dir2

foreach ( $file in $files )
{
    $dir2 = $dir + $file;
    $dir2
    New-Item $dir2;
    Set-Content $dir2 '[]';
}
