$files = @('Protoss_DirectDrop_Benzene_Zerg.txt',
'Protoss_DirectDrop_Destination_Zerg.txt',
'Protoss_DirectDrop_Heartbreak Ridge_Zerg.txt',
'Protoss_DirectDrop_Aztec_Zerg.txt',
'Protoss_DirectDrop_Tau Cross_Zerg.txt',
'Protoss_DirectDrop_Andromeda_Zerg.txt',
'Protoss_DirectDrop_Circuit Breaker_Zerg.txt',
'Protoss_DirectDrop_Empire of the Sun_Zerg.txt',
'Protoss_DirectDrop_Fortress_Zerg.txt',
'Protoss_DirectDrop_Python_Zerg.txt',
'Protoss_Drop_Benzene_Zerg.txt',
'Protoss_Drop_Destination_Zerg.txt',
'Protoss_Drop_Heartbreak Ridge_Zerg.txt',
'Protoss_Drop_Aztec_Zerg.txt',
'Protoss_Drop_Tau Cross_Zerg.txt',
'Protoss_Drop_Andromeda_Zerg.txt',
'Protoss_Drop_Circuit Breaker_Zerg.txt',
'Protoss_Drop_Empire of the Sun_Zerg.txt',
'Protoss_Drop_Fortress_Zerg.txt',
'Protoss_Drop_Python_Zerg.txt',
'Protoss_ZealotRush_Benzene_Zerg.txt',
'Protoss_ZealotRush_Destination_Zerg.txt',
'Protoss_ZealotRush_Heartbreak Ridge_Zerg.txt',
'Protoss_ZealotRush_Aztec_Zerg.txt',
'Protoss_ZealotRush_Tau Cross_Zerg.txt',
'Protoss_ZealotRush_Andromeda_Zerg.txt',
'Protoss_ZealotRush_Circuit Breaker_Zerg.txt',
'Protoss_ZealotRush_Empire of the Sun_Zerg.txt',
'Protoss_ZealotRush_Fortress_Zerg.txt',
'Protoss_ZealotRush_Python_Zerg.txt',
'Protoss_DirectDrop_Benzene_Terran.txt',
'Protoss_DirectDrop_Destination_Terran.txt',
'Protoss_DirectDrop_Heartbreak Ridge_Terran.txt',
'Protoss_DirectDrop_Aztec_Terran.txt',
'Protoss_DirectDrop_Tau Cross_Terran.txt',
'Protoss_DirectDrop_Andromeda_Terran.txt',
'Protoss_DirectDrop_Circuit Breaker_Terran.txt',
'Protoss_DirectDrop_Empire of the Sun_Terran.txt',
'Protoss_DirectDrop_Fortress_Terran.txt',
'Protoss_DirectDrop_Python_Terran.txt',
'Protoss_Drop_Benzene_Terran.txt',
'Protoss_Drop_Destination_Terran.txt',
'Protoss_Drop_Heartbreak Ridge_Terran.txt',
'Protoss_Drop_Aztec_Terran.txt',
'Protoss_Drop_Tau Cross_Terran.txt',
'Protoss_Drop_Andromeda_Terran.txt',
'Protoss_Drop_Circuit Breaker_Terran.txt',
'Protoss_Drop_Empire of the Sun_Terran.txt',
'Protoss_Drop_Fortress_Terran.txt',
'Protoss_Drop_Python_Terran.txt',
'Protoss_ZealotRush_Benzene_Terran.txt',
'Protoss_ZealotRush_Destination_Terran.txt',
'Protoss_ZealotRush_Heartbreak Ridge_Terran.txt',
'Protoss_ZealotRush_Aztec_Terran.txt',
'Protoss_ZealotRush_Tau Cross_Terran.txt',
'Protoss_ZealotRush_Andromeda_Terran.txt',
'Protoss_ZealotRush_Circuit Breaker_Terran.txt',
'Protoss_ZealotRush_Empire of the Sun_Terran.txt',
'Protoss_ZealotRush_Fortress_Terran.txt',
'Protoss_ZealotRush_Python_Terran.txt',
'Protoss_DirectDrop_Benzene_Protoss.txt',
'Protoss_DirectDrop_Destination_Protoss.txt',
'Protoss_DirectDrop_Heartbreak Ridge_Protoss.txt',
'Protoss_DirectDrop_Aztec_Protoss.txt',
'Protoss_DirectDrop_Tau Cross_Protoss.txt',
'Protoss_DirectDrop_Andromeda_Protoss.txt',
'Protoss_DirectDrop_Circuit Breaker_Protoss.txt',
'Protoss_DirectDrop_Empire of the Sun_Protoss.txt',
'Protoss_DirectDrop_Fortress_Protoss.txt',
'Protoss_DirectDrop_Python_Protoss.txt',
'Protoss_Drop_Benzene_Protoss.txt',
'Protoss_Drop_Destination_Protoss.txt',
'Protoss_Drop_Heartbreak Ridge_Protoss.txt',
'Protoss_Drop_Aztec_Protoss.txt',
'Protoss_Drop_Tau Cross_Protoss.txt',
'Protoss_Drop_Andromeda_Protoss.txt',
'Protoss_Drop_Circuit Breaker_Protoss.txt',
'Protoss_Drop_Empire of the Sun_Protoss.txt',
'Protoss_Drop_Fortress_Protoss.txt',
'Protoss_Drop_Python_Protoss.txt',
'Protoss_ZealotRush_Benzene_Protoss.txt',
'Protoss_ZealotRush_Destination_Protoss.txt',
'Protoss_ZealotRush_Heartbreak Ridge_Protoss.txt',
'Protoss_ZealotRush_Aztec_Protoss.txt',
'Protoss_ZealotRush_Tau Cross_Protoss.txt',
'Protoss_ZealotRush_Andromeda_Protoss.txt',
'Protoss_ZealotRush_Circuit Breaker_Protoss.txt',
'Protoss_ZealotRush_Empire of the Sun_Protoss.txt',
'Protoss_ZealotRush_Fortress_Protoss.txt',
'Protoss_ZealotRush_Python_Protoss.txt')

$dir = 'E:\Test\UAlbertaBot\bin\bwapi-data\logging\';
$dir2 = $dir + $files[0];
$dir2

foreach ( $file in $files )
{
    $dir2 = $dir + $file;
    $dir2
    New-Item $dir2;
    Set-Content $dir2 ([byte[]][char[]] "[]") -Encoding Byte
}
